name: Build & Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: nextjs-backend-application  # Set this to your application's name
  NODE_VERSION: '22'                             # Node.js version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Create .env for build process
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env

      - name: npm install and build
        run: |
          npm install
          npm run build 
          
      - name: Copy static assets to standalone folder
        run: |
          # cp -r public .next/standalone/
          cp -r .next/static .next/standalone/.next/

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: './.next/standalone'
          clean: true
          
      - name: Azure Logout
        run: az logout
